矩阵——空间的扭曲

In [17]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 复制 分配新内存
print(A)
print(A.T)  # 转置矩阵（对称矩阵A=A.T）
print(A + B)  # 按位加
print(A * B)  # 按位乘

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [18]:
print(A.sum())  # 所有元素求和 总是标量
print(A.sum(axis=1))  # 行求和
print(A.sum(axis=1, keepdims=True))  # 行求和 保持维度不变
print(A / A.sum())  # 广播机制 自动扩展维度以匹配形状

tensor(190.)
tensor([ 6., 22., 38., 54., 70.])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([[0.0000, 0.0053, 0.0105, 0.0158],
        [0.0211, 0.0263, 0.0316, 0.0368],
        [0.0421, 0.0474, 0.0526, 0.0579],
        [0.0632, 0.0684, 0.0737, 0.0789],
        [0.0842, 0.0895, 0.0947, 0.1000]])


向量的范数
矩阵的范数

In [21]:
a = torch.tensor([3.0, -4.0])
print(torch.norm(a))  # 向量的L2范数
print(torch.abs(a).sum())  # 向量的L1范数

print(torch.norm(A))  # 矩阵的F范数

tensor(5.)
tensor(7.)
tensor(49.6991)
