梯度

In [1]:
import torch

x = torch.arange(4.0, requires_grad=True)
print(x)
print(x.grad)

tensor([0., 1., 2., 3.], requires_grad=True)
None


In [8]:
x.grad.zero_()  # 梯度清零
y = 2 * torch.dot(x, x)
print(y)
y.backward()  # 反向传播计算梯度
x.grad == 4 * x  # x的梯度 dy/dx=4x

tensor(28., grad_fn=<MulBackward0>)


tensor([True, True, True, True])

In [3]:
x.grad.zero_()  # 梯度清零
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [4]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [5]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(True)